### ISSUE TITLE
Injector: Types Consistency 

### ISSUE THREAD

**Issue by ricardoffmartins** [ZinkDigital/boson#10]
Hi @NigeWarren 

When we are applying a change to a field of a NettyBson should the change of types be allowed?
Assuming we have a field named Temperature that corresponds to a Double

Temperature -> Double

Should it be possible to change the type to a different one as a result of a function applied to it?

Example:
Injector.modify(NettyBson, fieldID, x: Double => { "value is " + x } )

The type would then change:
Temperature -> String
And this would need to be reflected in the NettyBson itself (by changing the type)

Do you think this would be a good thing to habe or should we protect our code against type changes?

Best regards,
Ricardo Martins

**Comment by NigeWarren** [comment]
Hi @ricardoffmartins as discussed we should apply the constraint ...

 InjectorFunction = Function[IT, OT] where IT == OT
