### ISSUE TITLE
Buffer Type should not be apparent in Interface.

### ISSUE THREAD

**Issue by NigeWarren** [ZinkDigital/boson#2]
As it stands the BufferType is apparent in the interface. The buffer type should be masked in the interface.

**Comment by tiagofiliperdy** [comment]
Hey Nigel,
I'm not sure of what you want, at the moment we have 5 methods that receive each one a different bufferType, are you asking to group those 5 into only 1? If so, the argument type, in Scala, would have to be Any, not ensuring that who uses the Library would initialize a NettyBson with a buffer.
Same happens in Java.

**Comment by NigeWarren** [comment]
As discussed - Boson should only operate on Java 8+ Buffers and argueably byte[].

Overall we need to reduce the dependencies on other LIbraries and the encoding of those dependices in the API.

**Comment by NigeWarren** [comment]
See also #18 for example interface that uses only byte[] and ByteBuffer

**Comment by NigeWarren** [comment]
Implementation of shared interfaces deprecates this issue
