### ISSUE TITLE
Simple example of library use at top of README

### ISSUE THREAD

**Issue by NigeWarren** [ZinkDigital/boson#3]
The readme.md file should include a very simple example of both Java and Scala use of the library, to show a simple extraction of a value for an example Bson and Json document. 

This could be extracted from the tests.

**Comment by NigeWarren** [comment]
As we change things we need to keep the Readme in line with the new API(s) and symantics via teh implementation

**Comment by ricardoffmartins** [comment]
Issue #3. ReadMe already contains API examples for the Java API and Scala API.
