### ISSUE TITLE
Test to prove arbitrary Case Classes can be extracted

### ISSUE THREAD

**Issue by NigeWarren** [ZinkDigital/boson#38]
@tiagofiliperdy @ricardoffmartins please ensure that there are tests to extract embedded case classes

i.e.

case class Thing1(val height : Float, val overActive : Boolean)
case class Thing2(val age : Int, val  thing1 : Thing1)

 and extract Thing2 from Json / Bson

**Comment by MrLucasFischer** [comment]
Closing this issue as #57 implemented the desired changes
