### ISSUE TITLE
Java API Generic Type Erasure

### ISSUE THREAD

**Issue by tiagofiliperdy** [ZinkDigital/boson#41]
Current Java API:
static <T> Boson extractor(String expression, Consumer<T> extractFunction) {
     return new BosonExtractor<>(expression,extractFunction);
}

The goal is to get the generic type T at run-time without changing the API, in order to do it @NigeWarren suggested to use java.lang.reflect, one possible solution was:

Method  method = Boson.class.getMethod("extractor", String.class, Consumer.class);
Type[] genericParameterTypes  = method.getGenericParameterTypes();
if(genericParameterTypes[1] instanceof ParameterizedType) {
   ParameterizedType aType = (ParameterizedType)genericParameterTypes[1];
   Type[] parameterArgTypes = aType.getActualTypeArguments();
   Class parameterArgClass = (Class) parameterArgTypes[0];
}

But in the last line an exception is thrown, java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class, and this happens because in position zero of the parameterArgTypes[] the type is T.

**Comment by NigeWarren** [comment]
Noting in the above that the Consumer is a Consumer of type <T>

https://docs.oracle.com/javase/8/docs/api/java/util/function/Consumer.html

At compile time the definition of Consumer will make a concrete Type of T (e.g. String, House, Integer), the challenge is to Discover the type of T at runtime and to write to appropriate code to transform the data in the BSON/JSON into  the appropriate transformations as is done in the Scala code.

**Comment by NigeWarren** [comment]
@tiagofiliperdy @ricardoffmartins Guys looks like the resolution is the TypeTools library hence ...

 ``` 
    <dependencies>
        <dependency>
            <groupId>net.jodah</groupId>
            <artifactId>typetools</artifactId>
            <version>0.5.0</version>
        </dependency>
    </dependencies>
```


Thence ...

```
import net.jodah.typetools.TypeResolver;

import java.nio.ByteBuffer;
import java.util.function.Consumer;
import java.util.function.Function;

public class Main {

    public static void main(String[] args) {

        Consumer<String> strConsumer = str  -> System.out.println(str);
        func("..Denis", strConsumer);

        Consumer<Integer> intConsumer = intgr  -> System.out.println(intgr);
        func("..age", intConsumer);

        Consumer<ByteBuffer> buffConsumer = buff  -> System.out.println(buff.toString());
        func("..age", buffConsumer);

    }


    public static <T> void func(String str, Consumer<T> cons) {
        try {
            Class<?>[] typeArgs = TypeResolver.resolveRawArguments(Function.class, cons.getClass());
            System.out.println(typeArgs[0].getName());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
```
Gives you access to the complete runtime for the class i.e. the Class instance from which you can make new instances etc etc.

**Comment by NigeWarren** [comment]
@tiagofiliperdy @megidio @MrLucasFischer @ricardoffmartins - Im going to close this one and direct the conversation to #48
