### ISSUE TITLE
Codecs - Injectors implementation

### ISSUE THREAD

**Issue by ricardoffmartins** [ZinkDigital/boson#43]
The codecs are built with the help of a Object named CodecObject which has a function named toCodec that receives the Input from the user. This input can be an encoded byte[] (BSON) or a String (JSON). The correct codec is picked implicitly inside the Object.

The Codecs are working for extraction only. No work has been done in terms of injectors. 
The CodecBson uses a Bytebuf from Netty. 
The CodecJson uses a StringBuilder, due to performance.

So all code relative to Injectors is still to be implemented

**Comment by MrLucasFischer** [comment]
Closing this issue as #57 implemented the desired issues
