### ISSUE TITLE
Javadoc failure prevents publish of Boson Java 

### ISSUE THREAD

**Issue by NigeWarren** [ZinkDigital/boson#44]
SBT is sending the "-g:none" flag to 'javadoc' which is preventing the javadoc phase of publish working .

We need to make sbt send the -g flag to only javac in order to be able to publish all of the artifacts to sonatype correctly

**Comment by NigeWarren** [comment]
@megidio Have we got around the javadoc issue ? - can we please close this if we can publish Boson Java ?

**Comment by ricardoffmartins** [comment]
Issue #44 resolved. Publishing artefacts no longer raises issues with Javadoc
