### ISSUE TITLE
Generic type T[T[T]] java problem

### ISSUE THREAD

**Issue by MrLucasFischer** [ZinkDigital/boson#48]
Currently in BosonExtractor.java, using typetools library its impossible to retain the type T[T], it only allows us to retain the outter type, which prevents the validation of the type given by the user when it comes to Seq[A], A being any primitive type. Ideally we would also want to retain type A in a type T[A].

**Comment by NigeWarren** [comment]
@MrLucasFischer please see https://github.com/jhalterman/typetools/pull/12

**Comment by NigeWarren** [comment]
Which is evidence that it can be done - doesnt seem to be merged but you may be able to use the code ???

**Comment by MrLucasFischer** [comment]
@NigeWarren On a `Consumer<scala.collection.immutable.Seq<Double>>` : 
```java
Class<?>[] typeArgs = TypeResolver.resolveRawArguments(Function.class, cons.getClass());
// typeArgs[0] == interface scala.collection.immutable.Seq
Class<?> nextArg = TypeResolver.resolveRawArgument(typeArgs[0], typeArgs[0]);
// nextArg == class net.jodah.typetools.TypeResolver$Unknown
```
I'm not sure if it's because the parameterized type `Double` is only consumed at run-time , hence at compile-time this type will not have been used yet returning a type `Unknown` for unused types, or if it's a different problem altogether.

**Comment by NigeWarren** [comment]
So it seems that jhalterman/typetools#12  is the way to go - we could ask them to merge the PR or we will need to copy out the code from the PR if they dont merge it. It would be wise and proper to ask for merge first  but it doesnt look like much activity this year has taken place?

**Comment by NigeWarren** [comment]
@tiagofiliperdy @MrLucasFischer - Guys  - Jonathan from typetools kindly mailed me back with the following ..
"That pull request never quite got to the point of implementing GenericType support. It's something I just never got to. I'd be happy to take a revised PR that adds support for this. For Boson in particular, I might recommend you look at ClassMate, which does provide a generic type construct, thought it doesn't support lambda type resolution."

So we need to have a look at ClassMate which may help

**Comment by MrLucasFischer** [comment]
@NigeWarren I haven't been testing with java collections with `Consumer<java.util.List<java.lang.Double>>` because I believe it's not supported yet, I think we only still support extracting multiple values as a `scala.collection.immutable.Seq`, we might have to work on differentiating an API call from the Java API and from the Scala API in order to correctly support collections that best fit those API's. This is something both me and @tiagofiliperdy wanted to ask you: Does the Java module have to be entirely written in Java or only the API that is exposed to the user, and the rest could be written in Scala ? This, I think, would solve some of the problems we're facing because we could use Shapeless as @tiagofiliperdy and @ricardoffmartins have already done in the scala module.

**Comment by MrLucasFischer** [comment]
@NigeWarren I've been looking at ClassMate for the past hour and I don't think it solves our problem. In the email that Jonathan from typetools sent you, he said that ClassMate does not support lambda type resolution which I think is what we are trying to solve. The `ResolvedType` that ClassMate returned me for `Consumer<T>` was a Lambda as we should expect, and `typeParametersFor(Consumer.class)` came back empty, so I believe ClassMate might not be that helpful for us.

**Comment by NigeWarren** [comment]
@MrLucasFischer @tiagofiliperdy - In essence the Java interface should use Java idioms and Libraries - so Classes and examples that are for the java system should use Java Idioms and Classes and likewise the Scala system should use Scala idioms and Class library

In the example that you give there is nothing to stop you converting the collection Type from Seq to java.util.List on the way back out through the API for example. More than happy for the underlying machinery to use any amount of scala libs  so long as by the time Objects emerge through the interface they suit the given environment.

Take a look at JavaConverters here https://docs.scala-lang.org/overviews/collections/conversions-between-java-and-scala-collections.html  please

**Comment by NigeWarren** [comment]
On type parameter retention then I guess we should use the code in the PR and then work it back into Jonathans library typetools and put a PR on that Library - or use the branch in typetools to resubmit the patch.

**Comment by MrLucasFischer** [comment]
Closing this as implementing #51 seems to have solved our problem.
