### ISSUE TITLE
ReThink on Collections of Types

### ISSUE THREAD

**Issue by NigeWarren** [ZinkDigital/boson#51]
@tiagofiliperdy  @ricardoffmartins  @MrLucasFischer @megidio 

Just been writing up the REAME.md for the new version of Boson and springs to mind that we may not wish to follow the design principle of JSON path to return a Collection if it maps to a JSON array.

We could in preference invoke the given Function Consumer<T> for each instance of the type T in the array. There are a number of uses case where this would improve the overall 'flow' of information in a reactive system. 

It would also prevent issues such as #48 by introducing the rule that the consuming type must be a top level ADT (Scala case class) or non Parameterised Object instance (Java).

This could still be of arbitrary complexity - i.e. contain other Classes including Collections of nested items. However when consuming arrays of objects the function gets called for each instance that matches with the given BSON path expression.

Hence rather than compiling the Seq or List of items to send to the function we simply apply the function any instance of the given target instance as soon as we construct it. In this way Boson 'iterates' over the array rather than compiling the array and then the consuming function iterates over it.

This would

Reduce Complexity 
Increase utility and performance

Comments ???

**Comment by MrLucasFischer** [comment]
Closing this issue because it has been implemented in commit d188299461d6ad142fb33ee3fadfbeb9070fa2bd and cleaned up in commit 395450b03a7a0db1fa1ac1108bbeb1d7033160da
